"""create audit_reports table

Revision ID: 7cb329052a89
Revises: 9dfa1b521604
Create Date: 2026-08-07 19:34:17.578006

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7cb329052a89'
down_revision: Union[str, Sequence[str], None] = '9dfa1b521604'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('audit_reports',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('framework_key', sa.String(), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=False),
    sa.Column('total_controls', sa.Integer(), nullable=False),
    sa.Column('operating_controls', sa.Integer(), nullable=False),
    sa.Column('total_supporting_cases', sa.Integer(), nullable=False),
    sa.Column('pdf_path', sa.String(), nullable=False),
    sa.Column('json_path', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('audit_reports')
    # ### end Alembic commands ###
