"""add events and incidents tables, dual-parent labels and remediation actions

Revision ID: a82ede822cac
Revises: a93346850736
Create Date: 2026-08-08 12:08:05.509128

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a82ede822cac'
down_revision: Union[str, Sequence[str], None] = 'a93346850736'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('incidents',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('verdict', sa.String(), nullable=False),
    sa.Column('score', sa.Integer(), nullable=False),
    sa.Column('detection_types', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('framework_mappings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('window_start', sa.DateTime(timezone=True), nullable=False),
    sa.Column('window_end', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('source_ip', sa.String(), nullable=True),
    sa.Column('geo', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('action', sa.String(), nullable=False),
    sa.Column('target', sa.String(), nullable=True),
    sa.Column('bytes', sa.BigInteger(), nullable=True),
    sa.Column('device', sa.String(), nullable=True),
    sa.Column('outcome', sa.String(), nullable=True),
    sa.Column('raw', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('incident_id', sa.Uuid(), nullable=True),
    sa.ForeignKeyConstraint(['incident_id'], ['incidents.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    # Batch mode: SQLite has no native ALTER TABLE ALTER COLUMN / ADD CONSTRAINT, so these
    # column-nullability + FK + CHECK changes on existing tables must go through Alembic's
    # batch (recreate-table) mode to work on both SQLite and Postgres.
    with op.batch_alter_table('labels') as batch_op:
        batch_op.add_column(sa.Column('incident_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('case_id', existing_type=sa.Uuid(), nullable=True)
        batch_op.create_foreign_key(
            'fk_labels_incident_id', 'incidents', ['incident_id'], ['id'], ondelete='CASCADE'
        )
        batch_op.create_check_constraint(
            'ck_labels_exactly_one_parent', '(case_id IS NOT NULL) != (incident_id IS NOT NULL)'
        )
    with op.batch_alter_table('remediation_actions') as batch_op:
        batch_op.add_column(sa.Column('incident_id', sa.Uuid(), nullable=True))
        batch_op.alter_column('case_id', existing_type=sa.Uuid(), nullable=True)
        batch_op.create_foreign_key(
            'fk_remediation_actions_incident_id',
            'incidents',
            ['incident_id'],
            ['id'],
            ondelete='CASCADE',
        )
        batch_op.create_check_constraint(
            'ck_remediation_actions_exactly_one_parent',
            '(case_id IS NOT NULL) != (incident_id IS NOT NULL)',
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('remediation_actions') as batch_op:
        batch_op.drop_constraint('ck_remediation_actions_exactly_one_parent', type_='check')
        batch_op.drop_constraint('fk_remediation_actions_incident_id', type_='foreignkey')
        batch_op.alter_column('case_id', existing_type=sa.Uuid(), nullable=False)
        batch_op.drop_column('incident_id')
    with op.batch_alter_table('labels') as batch_op:
        batch_op.drop_constraint('ck_labels_exactly_one_parent', type_='check')
        batch_op.drop_constraint('fk_labels_incident_id', type_='foreignkey')
        batch_op.alter_column('case_id', existing_type=sa.Uuid(), nullable=False)
        batch_op.drop_column('incident_id')
    op.drop_table('events')
    op.drop_table('incidents')
    # ### end Alembic commands ###
