"""add case recipients, remediation actions, training recommendations

Revision ID: a93346850736
Revises: 7cb329052a89
Create Date: 2026-08-07 20:14:10.937848

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'a93346850736'
down_revision: Union[str, Sequence[str], None] = '7cb329052a89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('training_recommendations',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('recipient', sa.String(), nullable=False),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('top_indicator_id', sa.String(), nullable=False),
    sa.Column('top_indicator_title', sa.String(), nullable=False),
    sa.Column('recommendation', sa.Text(), nullable=False),
    sa.Column('first_flagged_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('recipient')
    )
    op.create_table('remediation_actions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('case_id', sa.Uuid(), nullable=False),
    sa.Column('step_id', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('actor', sa.String(), nullable=False),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # server_default so this NOT NULL column can be added to a table that may already
    # have rows (existing cases get an empty recipient list, not a migration failure).
    op.add_column(
        'cases',
        sa.Column(
            'to_addresses',
            sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'),
            nullable=False,
            server_default='[]',
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('cases', 'to_addresses')
    op.drop_table('remediation_actions')
    op.drop_table('training_recommendations')
    # ### end Alembic commands ###
